# Generated by Django 4.1.4 on 2022-12-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series", models.IntegerField()),
                ("number", models.IntegerField(unique=True)),
                ("release_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("balanse", models.FloatField()),
                (
                    "year_in_school",
                    models.CharField(
                        choices=[
                            ("FR", "Freshman"),
                            ("SO", "Sophomore"),
                            ("JR", "Junior"),
                            ("SR", "Senior"),
                            ("GR", "Graduate"),
                        ],
                        default="FR",
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
