# Generated by Django 4.1.4 on 2022-12-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="card", name="year_in_school",),
        migrations.AddField(
            model_name="card",
            name="status",
            field=models.CharField(
                choices=[
                    ("AC", "Активированная"),
                    ("NO_AC", "Не активированная"),
                    ("EX", "Просроченная"),
                ],
                default="NO_AC",
                max_length=5,
            ),
        ),
    ]
